stages:
  data_ingestion:
    cmd: python src/student_performance/pipeline/training_pipeline.py
    deps:
    - src/student_performance/pipeline/training_pipeline.py
    - src/student_performance/components/data_ingestion.py
    - config/config.yaml
    outs:
    - artifacts/data_ingestion/data.csv

  data_transformation:
    cmd: python src/student_performance/pipeline/training_pipeline.py
    deps:
    - src/student_performance/pipeline/training_pipeline.py
    - src/student_performance/components/data_transformation.py
    - artifacts/data_ingestion/data.csv
    outs:
    - artifacts/data_transformation/train.csv
    - artifacts/data_transformation/test.csv
    - artifacts/data_transformation/preprocessor.pkl

  model_trainer:
    cmd: python src/student_performance/pipeline/training_pipeline.py
    deps:
    - src/student_performance/pipeline/training_pipeline.py
    - src/student_performance/components/model_trainer.py
    - artifacts/data_transformation/train.csv
    - artifacts/data_transformation/test.csv
    params:
    - ElasticNet.alpha
    - ElasticNet.l1_ratio
    - RandomForest.n_estimators
    - XGBoost.learning_rate
    outs:
    - artifacts/model_trainer/model.pkl

  model_evaluation:
    cmd: python src/student_performance/pipeline/training_pipeline.py
    deps:
    - src/student_performance/pipeline/training_pipeline.py
    - src/student_performance/components/model_evaluation.py
    - artifacts/model_trainer/model.pkl
    - artifacts/data_transformation/test.csv
    metrics:
    - artifacts/model_evaluation/metrics.json:
        cache: false
