ElasticNet:
  alpha: 0.2
  l1_ratio: 0.1

RandomForest:
  n_estimators: 100
  max_depth: 10
  min_samples_split: 2
  min_samples_leaf: 1
  random_state: 42

XGBoost:
  n_estimators: 100
  max_depth: 6
  learning_rate: 0.1
  subsample: 0.8
  colsample_bytree: 0.8
  random_state: 42

CatBoost:
  iterations: 100
  depth: 6
  learning_rate: 0.1
  random_seed: 42
  verbose: False

LightGBM:
  n_estimators: 100
  max_depth: 6
  learning_rate: 0.1
  subsample: 0.8
  colsample_bytree: 0.8
  random_state: 42

hyperparameter_tuning:
  cv_folds: 5
  n_trials: 100
  timeout: 3600

model_evaluation:
  target_column: math_score
  test_size: 0.2
  random_state: 42
  expected_accuracy: -0.5  # Minimum R2 score threshold for model acceptance (temporarily lowered for debugging)
